# Generated by Django 3.0.5 on 2020-05-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapcode',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='scrapcode',
            name='prof_Name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
