# Generated by Django 3.0.5 on 2020-05-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapdata', '0002_auto_20200525_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapcode',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
