# Generated by Django 3.0.5 on 2020-05-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapdata', '0005_auto_20200526_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapcode',
            name='phone_number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
