# Generated by Django 3.0.5 on 2020-05-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapdata', '0007_auto_20200526_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapcode',
            name='department',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
